import type { Locale } from '@onetappe/mobile-kit';

/** Worker app copy. A missing Hindi string is a type error. */
const en = {
  signInTitle: 'One Tappe Partner — sign in with your mobile number',
  termsTitle: 'Before you start work',
  termsIntro: 'Please read and accept:',
  readDocument: 'Read',
  accept: 'I accept',
  onboardingTitle: 'Your application',
  onboardingIntro:
    'You can take jobs once your verification and training are complete and our team has approved you.',
  profileStep: 'Personal details',
  documentsStep: 'Documents',
  verificationStep: 'Verification',
  trainingStep: 'Training',
  approvalStep: 'Approval by One Tappe',
  done: 'Done',
  pending: 'Pending',
  rejected: 'Needs attention',
  onboardingHelp: 'Your onboarding coordinator will help you complete these steps.',
  suspended: 'Your account is not active for jobs right now',
  online: 'You are online — offers will appear here',
  offline: 'You are offline',
  goOnline: 'Go online',
  goOffline: 'Go offline',
  locationNeeded: 'Allow location to go online, so we can offer you nearby jobs.',
  offersTitle: 'Job offers',
  noOffers: 'No offers right now.',
  expiresIn: 'Answer within',
  payout: 'Estimated pay',
  acceptJob: 'Accept',
  rejectJob: 'Not this one',
  rejectReason: 'Reason',
  offerGone: 'This offer is no longer available.',
  currentJob: 'Current job',
  openJob: 'Open job',
  jobTitle: 'Job',
  customer: 'Customer',
  address: 'Address',
  accessNotes: 'Notes',
  callCustomer: 'Call customer',
  navigate: 'Open in Google Maps',
  tasks: 'Tasks, in priority order',
  onTheWay: 'I am on the way',
  arrived: 'I have arrived',
  showId:
    'Show your One Tappe ID to the customer. They will give you the 4-digit start code after checking it.',
  startCode: 'Start code from the customer',
  startJob: 'Start job',
  inProgress: 'Job in progress',
  plannedEnd: 'Planned end',
  complete: 'Mark job complete',
  completed: 'Job completed. Thank you!',
  customerNoShow: 'Customer not available',
  noShowReason: 'What happened?',
  confirmNoShow: 'Report customer not available',
  earnings: 'Earnings',
  history: 'Job history',
  sos: 'SOS',
  sosTitle: 'Are you unsafe?',
  sosIntro:
    'This alerts the One Tappe safety team immediately with your location. Stop work and move to a safe place. If you are in danger, also call 112.',
  sosSend: 'Send SOS now',
  sosSent: 'The safety team has been alerted and will call you right away.',
  signOut: 'Sign out',
  signOutEverywhere: 'Sign out of all devices',
  language: 'हिंदी',
  home: 'Home',
  help: 'Help',
  codeIncorrect: 'That code is not correct. Check it with the customer.',
  codeLocked: 'Too many wrong codes. Operations has been alerted and will call you.',
  totals: 'Totals',
  noEarnings: 'No earnings yet.',
} as const;

type Strings = { readonly [K in keyof typeof en]: string };

const hi: Strings = {
  signInTitle: 'One Tappe पार्टनर — अपने मोबाइल नंबर से साइन इन करें',
  termsTitle: 'काम शुरू करने से पहले',
  termsIntro: 'कृपया पढ़ें और स्वीकार करें:',
  readDocument: 'पढ़ें',
  accept: 'मैं स्वीकार करता/करती हूँ',
  onboardingTitle: 'आपका आवेदन',
  onboardingIntro:
    'सत्यापन और प्रशिक्षण पूरा होने और हमारी टीम की मंज़ूरी के बाद आप काम ले सकते हैं।',
  profileStep: 'व्यक्तिगत जानकारी',
  documentsStep: 'दस्तावेज़',
  verificationStep: 'सत्यापन',
  trainingStep: 'प्रशिक्षण',
  approvalStep: 'One Tappe की मंज़ूरी',
  done: 'पूरा',
  pending: 'बाकी',
  rejected: 'ध्यान दें',
  onboardingHelp: 'आपके ऑनबोर्डिंग समन्वयक ये चरण पूरे करने में मदद करेंगे।',
  suspended: 'आपका खाता अभी काम के लिए सक्रिय नहीं है',
  online: 'आप ऑनलाइन हैं — ऑफ़र यहाँ दिखेंगे',
  offline: 'आप ऑफ़लाइन हैं',
  goOnline: 'ऑनलाइन हों',
  goOffline: 'ऑफ़लाइन हों',
  locationNeeded: 'ऑनलाइन होने के लिए लोकेशन की अनुमति दें, ताकि हम पास के काम दे सकें।',
  offersTitle: 'काम के ऑफ़र',
  noOffers: 'अभी कोई ऑफ़र नहीं।',
  expiresIn: 'जवाब देने का समय',
  payout: 'अनुमानित कमाई',
  acceptJob: 'स्वीकार करें',
  rejectJob: 'यह नहीं',
  rejectReason: 'कारण',
  offerGone: 'यह ऑफ़र अब उपलब्ध नहीं है।',
  currentJob: 'मौजूदा काम',
  openJob: 'काम खोलें',
  jobTitle: 'काम',
  customer: 'ग्राहक',
  address: 'पता',
  accessNotes: 'निर्देश',
  callCustomer: 'ग्राहक को कॉल करें',
  navigate: 'Google Maps में खोलें',
  tasks: 'काम, प्राथमिकता के क्रम में',
  onTheWay: 'मैं रास्ते में हूँ',
  arrived: 'मैं पहुँच गया/गई हूँ',
  showId:
    'ग्राहक को अपना One Tappe पहचान पत्र दिखाएँ। जाँचने के बाद वे आपको 4 अंकों का शुरुआती कोड देंगे।',
  startCode: 'ग्राहक से मिला शुरुआती कोड',
  startJob: 'काम शुरू करें',
  inProgress: 'काम जारी है',
  plannedEnd: 'तय समाप्ति',
  complete: 'काम पूरा करें',
  completed: 'काम पूरा हुआ। धन्यवाद!',
  customerNoShow: 'ग्राहक उपलब्ध नहीं',
  noShowReason: 'क्या हुआ?',
  confirmNoShow: 'ग्राहक उपलब्ध नहीं — सूचना दें',
  earnings: 'कमाई',
  history: 'काम का इतिहास',
  sos: 'SOS',
  sosTitle: 'क्या आप असुरक्षित हैं?',
  sosIntro:
    'इससे One Tappe सुरक्षा टीम को आपकी लोकेशन के साथ तुरंत सूचना जाती है। काम रोकें और सुरक्षित जगह जाएँ। खतरे में हों तो 112 पर भी कॉल करें।',
  sosSend: 'अभी SOS भेजें',
  sosSent: 'सुरक्षा टीम को सूचना दे दी गई है, वे तुरंत आपको कॉल करेंगे।',
  signOut: 'साइन आउट',
  signOutEverywhere: 'सभी डिवाइस से साइन आउट करें',
  language: 'English',
  home: 'होम',
  help: 'सहायता',
  codeIncorrect: 'यह कोड सही नहीं है। ग्राहक से दोबारा पूछें।',
  codeLocked: 'बहुत बार गलत कोड। ऑपरेशंस टीम को सूचना दी गई है, वे आपको कॉल करेंगे।',
  totals: 'कुल',
  noEarnings: 'अभी कोई कमाई नहीं।',
};

export const strings: Record<Locale, Strings> = { en, hi };

/** Earnings entry types as workers read them. */
export const EARNING_TYPES: Record<Locale, Record<string, string>> = {
  en: {
    JOB: 'Job',
    TRAVEL: 'Travel',
    WAITING: 'Waiting time',
    CANCELLATION: 'Cancellation pay',
    INCENTIVE: 'Incentive',
    ADJUSTMENT: 'Adjustment',
  },
  hi: {
    JOB: 'काम',
    TRAVEL: 'यात्रा',
    WAITING: 'इंतज़ार का समय',
    CANCELLATION: 'रद्दीकरण भुगतान',
    INCENTIVE: 'प्रोत्साहन',
    ADJUSTMENT: 'समायोजन',
  },
};

/** Job statuses as workers read them. */
export const JOB_STATUS: Record<Locale, Record<string, string>> = {
  en: {
    ASSIGNED: 'Accepted — start when it is time',
    EN_ROUTE: 'On the way',
    ARRIVED: 'Arrived — waiting for start code',
    IN_PROGRESS: 'In progress',
    COMPLETED: 'Completed',
    CLOSED: 'Closed',
    CANCELLED: 'Cancelled',
    NO_SHOW: 'Customer not available',
    ON_HOLD: 'On hold — operations will contact you',
  },
  hi: {
    ASSIGNED: 'स्वीकार किया — समय पर शुरू करें',
    EN_ROUTE: 'रास्ते में',
    ARRIVED: 'पहुँच गए — शुरुआती कोड का इंतज़ार',
    IN_PROGRESS: 'जारी',
    COMPLETED: 'पूरा',
    CLOSED: 'बंद',
    CANCELLED: 'रद्द',
    NO_SHOW: 'ग्राहक उपलब्ध नहीं',
    ON_HOLD: 'रोका गया — ऑपरेशंस टीम संपर्क करेगी',
  },
};
