import type { Locale } from '@onetappe/mobile-kit';

/** Customer app copy. A missing Hindi string is a type error. */
const en = {
  appTitle: 'One Tappe',
  signInTitle: 'Sign in with your mobile number',
  termsTitle: 'Before you continue',
  termsIntro: 'Please read and accept:',
  accept: 'I accept',
  profileTitle: 'Your name',
  fullName: 'Full name',
  saveName: 'Save',
  locationTitle: 'Where do you need the service?',
  locationIntro: 'We use your location to find your address. You can adjust the pin and details.',
  useMyLocation: 'Use my current location',
  locationDenied: 'Location permission was not given. Enter your pincode and address.',
  locationFound: 'Location found',
  pincode: 'Pincode',
  houseNumber: 'House / flat number',
  building: 'Building / society (optional)',
  street: 'Street / sector (optional)',
  landmark: 'Landmark (optional)',
  city: 'City',
  accessNotes: 'Notes for the professional (optional)',
  saveAddress: 'Save address',
  notServed: 'We are not in this area yet. We will let you know when we are.',
  homeTitle: 'What do you need?',
  from: 'from',
  minutes: 'min',
  myBookings: 'My bookings',
  help: 'Help',
  tasksTitle: 'What should be done?',
  whenTitle: 'When?',
  noSlots: 'No free times that day. Try another day.',
  priceTitle: 'Price',
  total: 'Total',
  addressTitle: 'Address',
  bookNow: 'Book and pay',
  priceChanged: 'The price has changed. Please check the new price.',
  noAvailability: 'That time was just taken. Please choose another time.',
  outsideHours: 'That time is outside service hours. Please choose another time.',
  payTitle: 'Payment',
  payWithin: 'Pay by',
  payNow: 'Pay now',
  checkingPayment: 'Checking your payment with the bank…',
  paymentPending:
    'We have not received your payment yet. If money was deducted, it will be confirmed shortly — no need to pay again.',
  iHavePaid: 'I have paid — check again',
  testPaymentTitle: 'Test payment',
  testPaymentIntro: 'This is a test environment. No money moves.',
  testPay: 'Pay (test)',
  testFail: 'Fail (test)',
  gatewayUnavailable:
    'We could not reach the payment gateway. Your money is safe; try again shortly.',
  statusTitle: 'Your booking',
  bookingCode: 'Booking',
  scheduled: 'Time',
  originally: 'Originally',
  professional: 'Your professional',
  startCodeTitle: 'Start code',
  startCodeGuidance:
    'Share this code only after you have checked the professional’s ID. It is not a payment OTP.',
  showStartCode: 'Show start code',
  serviceStarted: 'Service started',
  serviceEnds: 'Planned end',
  rateTitle: 'How was it?',
  ratingComment: 'Comment (optional)',
  submitRating: 'Submit rating',
  thanksRating: 'Thank you for your rating.',
  invoice: 'Invoice',
  invoiceNumber: 'Invoice number',
  cancelBooking: 'Cancel booking',
  cancelReason: 'Reason for cancelling',
  confirmCancel: 'Cancel this booking',
  cancelled: 'Booking cancelled. Any refund due goes back to your original payment method.',
  support: 'Report a problem',
  supportTitle: 'How can we help?',
  category: 'What is it about?',
  subject: 'Subject',
  description: 'Tell us what happened',
  sendToSupport: 'Send',
  caseOpened: 'We have your request',
  yourCases: 'Your requests',
  sos: 'SOS — I feel unsafe',
  sosSent: 'Our safety team has been alerted and will call you right away.',
  noBookings: 'No bookings yet.',
  signOut: 'Sign out',
  signOutEverywhere: 'Sign out of all devices',
  language: 'हिंदी',
  readDocument: 'Read',
  addAddress: 'Add your address',
  findPincode: 'Find this pincode on the map',
  pincodeNotFound: 'We could not find that pincode. Use your current location instead.',
  asap: 'As soon as possible',
  paymentFailed: 'The payment did not go through and nothing was charged. Please try again.',
  workerId: 'ID',
  checkId: 'Check their One Tappe ID card matches this name and ID before letting them in.',
  home: 'Home',
  cancelRefundNote:
    'Any refund due under the cancellation policy goes back to your original payment method.',
  keepBooking: 'Keep booking',
  sosConfirm: 'Send an SOS to the One Tappe safety team? If you are in danger, also call 112.',
  sosSend: 'Send SOS',
} as const;

type Strings = { readonly [K in keyof typeof en]: string };

const hi: Strings = {
  appTitle: 'वन टैप',
  signInTitle: 'अपने मोबाइल नंबर से साइन इन करें',
  termsTitle: 'आगे बढ़ने से पहले',
  termsIntro: 'कृपया पढ़ें और स्वीकार करें:',
  accept: 'मैं स्वीकार करता/करती हूँ',
  profileTitle: 'आपका नाम',
  fullName: 'पूरा नाम',
  saveName: 'सहेजें',
  locationTitle: 'सेवा कहाँ चाहिए?',
  locationIntro:
    'आपका पता ढूँढने के लिए हम आपकी लोकेशन का उपयोग करते हैं। आप पिन और विवरण बदल सकते हैं।',
  useMyLocation: 'मेरी वर्तमान लोकेशन लें',
  locationDenied: 'लोकेशन की अनुमति नहीं मिली। अपना पिनकोड और पता डालें।',
  locationFound: 'लोकेशन मिल गई',
  pincode: 'पिनकोड',
  houseNumber: 'मकान / फ्लैट नंबर',
  building: 'बिल्डिंग / सोसायटी (वैकल्पिक)',
  street: 'गली / सेक्टर (वैकल्पिक)',
  landmark: 'पास की पहचान (वैकल्पिक)',
  city: 'शहर',
  accessNotes: 'कर्मी के लिए निर्देश (वैकल्पिक)',
  saveAddress: 'पता सहेजें',
  notServed: 'हम अभी इस क्षेत्र में नहीं हैं। शुरू होने पर आपको बताएँगे।',
  homeTitle: 'आपको क्या चाहिए?',
  from: 'से शुरू',
  minutes: 'मिनट',
  myBookings: 'मेरी बुकिंग',
  help: 'सहायता',
  tasksTitle: 'क्या-क्या करना है?',
  whenTitle: 'कब?',
  noSlots: 'उस दिन कोई समय खाली नहीं है। दूसरा दिन चुनें।',
  priceTitle: 'कीमत',
  total: 'कुल',
  addressTitle: 'पता',
  bookNow: 'बुक करें और भुगतान करें',
  priceChanged: 'कीमत बदल गई है। कृपया नई कीमत देखें।',
  noAvailability: 'यह समय अभी-अभी भर गया। कृपया दूसरा समय चुनें।',
  outsideHours: 'यह समय सेवा के घंटों से बाहर है। कृपया दूसरा समय चुनें।',
  payTitle: 'भुगतान',
  payWithin: 'भुगतान की अंतिम समय',
  payNow: 'अभी भुगतान करें',
  checkingPayment: 'बैंक से आपका भुगतान जाँचा जा रहा है…',
  paymentPending:
    'हमें अभी आपका भुगतान नहीं मिला है। अगर पैसे कट गए हैं तो जल्द पुष्टि हो जाएगी — दोबारा भुगतान न करें।',
  iHavePaid: 'मैंने भुगतान कर दिया — फिर जाँचें',
  testPaymentTitle: 'परीक्षण भुगतान',
  testPaymentIntro: 'यह परीक्षण वातावरण है। कोई पैसा नहीं कटता।',
  testPay: 'भुगतान (परीक्षण)',
  testFail: 'विफल (परीक्षण)',
  gatewayUnavailable:
    'भुगतान गेटवे से संपर्क नहीं हो पाया। आपका पैसा सुरक्षित है; थोड़ी देर में कोशिश करें।',
  statusTitle: 'आपकी बुकिंग',
  bookingCode: 'बुकिंग',
  scheduled: 'समय',
  originally: 'मूल समय',
  professional: 'आपके कर्मी',
  startCodeTitle: 'शुरुआती कोड',
  startCodeGuidance: 'कर्मी का पहचान पत्र देखने के बाद ही यह कोड बताएँ। यह भुगतान OTP नहीं है।',
  showStartCode: 'शुरुआती कोड दिखाएँ',
  serviceStarted: 'सेवा शुरू हो गई',
  serviceEnds: 'तय समाप्ति',
  rateTitle: 'सेवा कैसी रही?',
  ratingComment: 'टिप्पणी (वैकल्पिक)',
  submitRating: 'रेटिंग भेजें',
  thanksRating: 'आपकी रेटिंग के लिए धन्यवाद।',
  invoice: 'बिल',
  invoiceNumber: 'बिल नंबर',
  cancelBooking: 'बुकिंग रद्द करें',
  cancelReason: 'रद्द करने का कारण',
  confirmCancel: 'यह बुकिंग रद्द करें',
  cancelled: 'बुकिंग रद्द हो गई। देय रिफंड आपके मूल भुगतान माध्यम में वापस जाएगा।',
  support: 'समस्या बताएँ',
  supportTitle: 'हम कैसे मदद करें?',
  category: 'किस बारे में है?',
  subject: 'विषय',
  description: 'बताइए क्या हुआ',
  sendToSupport: 'भेजें',
  caseOpened: 'आपका अनुरोध मिल गया',
  yourCases: 'आपके अनुरोध',
  sos: 'SOS — मैं असुरक्षित महसूस कर रहा/रही हूँ',
  sosSent: 'हमारी सुरक्षा टीम को सूचना दे दी गई है, वे तुरंत आपको कॉल करेंगे।',
  noBookings: 'अभी कोई बुकिंग नहीं।',
  signOut: 'साइन आउट',
  signOutEverywhere: 'सभी डिवाइस से साइन आउट करें',
  language: 'English',
  readDocument: 'पढ़ें',
  addAddress: 'अपना पता जोड़ें',
  findPincode: 'यह पिनकोड नक्शे पर खोजें',
  pincodeNotFound: 'यह पिनकोड नहीं मिला। अपनी वर्तमान लोकेशन का उपयोग करें।',
  asap: 'जल्द से जल्द',
  paymentFailed: 'भुगतान नहीं हुआ और कोई पैसा नहीं कटा। कृपया फिर कोशिश करें।',
  workerId: 'आईडी',
  checkId: 'अंदर आने देने से पहले उनका One Tappe पहचान पत्र इस नाम और आईडी से मिलाएँ।',
  home: 'होम',
  cancelRefundNote: 'रद्दीकरण नीति के अनुसार देय रिफंड आपके मूल भुगतान माध्यम में वापस जाएगा।',
  keepBooking: 'बुकिंग रखें',
  sosConfirm: 'One Tappe सुरक्षा टीम को SOS भेजें? अगर आप खतरे में हैं, तो 112 पर भी कॉल करें।',
  sosSend: 'SOS भेजें',
};

export const strings: Record<Locale, Strings> = { en, hi };
export type StringKey = keyof typeof en;

/** Booking statuses as customers read them. */
export const STATUS: Record<Locale, Record<string, string>> = {
  en: {
    PENDING_PAYMENT: 'Waiting for payment',
    CONFIRMED: 'Confirmed — finding your professional',
    ON_HOLD: 'On hold — we will contact you',
    ASSIGNED: 'Professional assigned',
    EN_ROUTE: 'Professional is on the way',
    ARRIVED: 'Professional has arrived',
    IN_PROGRESS: 'Service in progress',
    COMPLETED: 'Service completed',
    CLOSED: 'Completed',
    CANCELLED: 'Cancelled',
    NO_SHOW: 'Missed visit',
    EXPIRED: 'Not paid in time',
  },
  hi: {
    PENDING_PAYMENT: 'भुगतान बाकी',
    CONFIRMED: 'पुष्ट — आपके लिए कर्मी खोजा जा रहा है',
    ON_HOLD: 'रोकी गई — हम आपसे संपर्क करेंगे',
    ASSIGNED: 'कर्मी तय हो गया',
    EN_ROUTE: 'कर्मी रास्ते में है',
    ARRIVED: 'कर्मी पहुँच गया है',
    IN_PROGRESS: 'सेवा जारी है',
    COMPLETED: 'सेवा पूरी हुई',
    CLOSED: 'पूरी हुई',
    CANCELLED: 'रद्द',
    NO_SHOW: 'विज़िट नहीं हो पाई',
    EXPIRED: 'समय पर भुगतान नहीं हुआ',
  },
};

/** Support categories a customer can pick (codes as the API accepts them). */
export const SUPPORT_CATEGORIES: Record<Locale, readonly (readonly [string, string])[]> = {
  en: [
    ['SERVICE_QUALITY', 'Quality of the service'],
    ['LATE_ARRIVAL', 'Professional was late'],
    ['NO_SHOW', 'Professional did not come'],
    ['BILLING', 'Price or bill'],
    ['REFUND', 'Refund'],
    ['DAMAGE', 'Something was damaged'],
    ['BEHAVIOUR', 'Behaviour of the professional'],
    ['APP_ISSUE', 'Problem with the app'],
    ['OTHER', 'Something else'],
  ],
  hi: [
    ['SERVICE_QUALITY', 'सेवा की गुणवत्ता'],
    ['LATE_ARRIVAL', 'कर्मी देर से आए'],
    ['NO_SHOW', 'कर्मी नहीं आए'],
    ['BILLING', 'कीमत या बिल'],
    ['REFUND', 'रिफंड'],
    ['DAMAGE', 'कुछ नुकसान हुआ'],
    ['BEHAVIOUR', 'कर्मी का व्यवहार'],
    ['APP_ISSUE', 'ऐप में समस्या'],
    ['OTHER', 'कुछ और'],
  ],
};
