/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Address {
  access_notes: string | null;
  archived_at: Timestamp | null;
  building: string | null;
  city_name: string;
  contact_name: string;
  contact_phone_e164: string;
  created_at: Generated<Timestamp>;
  house_number: string;
  id: Generated<string>;
  idempotency_key: string | null;
  is_default: Generated<boolean>;
  label: Generated<string>;
  landmark: string | null;
  lat: Numeric;
  lng: Numeric;
  locality_id: string | null;
  pincode: string;
  request_hash: string | null;
  street: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AppUser {
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  email: string | null;
  full_name: string | null;
  id: Generated<string>;
  phone_e164: string | null;
  phone_verified_at: Timestamp | null;
  preferred_locale: Generated<string>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface AuditLog {
  action: string;
  actor_role: string | null;
  actor_user_id: string | null;
  after: Json | null;
  before: Json | null;
  changed_fields: string[] | null;
  entity_id: string | null;
  entity_type: string;
  id: Generated<number>;
  metadata: Generated<Json>;
  occurred_at: Generated<Timestamp>;
  reason: string | null;
  request_id: string | null;
  source: string | null;
}

export interface AuthSession {
  client_app: string;
  created_at: Generated<Timestamp>;
  device_id: string | null;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_used_at: Generated<Timestamp>;
  mfa_verified_at: Timestamp | null;
  previous_refresh_token_hash: string | null;
  refresh_token_hash: string;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  rotated_at: Timestamp | null;
  user_agent: string | null;
  user_id: string;
}

export interface Booking {
  address_id: string;
  address_snapshot: Json;
  booking_code: Generated<string>;
  booking_type: string;
  cancellation_reason: string | null;
  cancelled_at: Timestamp | null;
  city_id: string;
  closed_at: Timestamp | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_user_id: string;
  currency: Generated<string>;
  customer_notes: string | null;
  customer_user_id: string;
  discount_paise: Generated<number>;
  id: Generated<string>;
  idempotency_key: string | null;
  locality_id: string;
  original_end: Timestamp;
  original_start: Timestamp;
  payment_due_by: Timestamp | null;
  payment_mode: Generated<string>;
  price_rule_id: string;
  promotion_id: string | null;
  reschedule_count: Generated<number>;
  scheduled_end: Timestamp;
  scheduled_start: Timestamp;
  service_id: string;
  service_option_id: string | null;
  source: string;
  status: Generated<string>;
  subtotal_paise: number;
  tax_paise: Generated<number>;
  total_paise: number;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  zone_id: string;
}

export interface BookingAssignment {
  booking_id: string;
  crew_slot: Generated<number>;
  end_reason: string | null;
  ended_at: Timestamp | null;
  id: Generated<string>;
  offer_expires_at: Timestamp;
  offered_at: Generated<Timestamp>;
  offered_by_user_id: string | null;
  reservation_id: string;
  responded_at: Timestamp | null;
  response_reason: string | null;
  source: string;
  status: Generated<string>;
  worker_id: string;
}

export interface BookingPriceLine {
  amount_paise: number;
  booking_id: string;
  code: string;
  id: Generated<number>;
  label: string;
  line_no: number;
  line_type: string;
  source_id: string | null;
}

export interface BookingRating {
  booking_id: string;
  comment: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  rated_by_user_id: string;
  rater_role: string;
  score: number;
}

export interface BookingScheduleChange {
  actor_role: string | null;
  actor_user_id: string | null;
  booking_id: string;
  id: Generated<number>;
  new_end: Timestamp;
  new_start: Timestamp;
  occurred_at: Generated<Timestamp>;
  previous_end: Timestamp;
  previous_start: Timestamp;
  reason: string;
  request_id: string | null;
  source: string;
}

export interface BookingStatusHistory {
  actor_role: string | null;
  actor_user_id: string | null;
  booking_id: string;
  event: string;
  from_status: string | null;
  id: Generated<number>;
  occurred_at: Generated<Timestamp>;
  reason: string | null;
  request_id: string | null;
  source: string;
  to_status: string;
}

export interface BookingStatusTransition {
  event: string;
  from_status: string;
  requires_reason: boolean;
  sources: string[];
  to_status: string;
}

export interface BookingTask {
  booking_id: string;
  id: Generated<string>;
  name: string;
  note: string | null;
  priority: number;
  service_task_id: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface BookingVerificationCode {
  attempts: Generated<number>;
  booking_id: string;
  code_hash: string;
  created_at: Generated<Timestamp>;
  max_attempts: Generated<number>;
  purpose: string;
  verified_at: Timestamp | null;
}

export interface BusinessSetting {
  description: string;
  key: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  value: Json;
}

export interface CancellationRule {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  min_minutes_before_start: number;
  refund_bp: number;
  service_id: string | null;
  valid_from: Timestamp;
  valid_to: Timestamp | null;
}

export interface ChargeRule {
  booking_type: string | null;
  city_id: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  end_minute: number | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: string;
  label: string;
  service_id: string | null;
  start_minute: number | null;
  taxable: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  valid_from: Timestamp;
  valid_to: Timestamp | null;
  value: number;
  weekdays: number[] | null;
  zone_id: string | null;
}

export interface City {
  code: string;
  country_code: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  state_name: string;
  time_zone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ConsentRecord {
  granted_at: Generated<Timestamp>;
  id: Generated<string>;
  ip: string | null;
  legal_document_id: string | null;
  purpose: string;
  source: string;
  user_id: string;
  withdrawn_at: Timestamp | null;
}

export interface CreditNote {
  amount_paise: number;
  credit_note_number: string;
  id: Generated<string>;
  invoice_id: string;
  issued_at: Generated<Timestamp>;
  reason: string;
  refund_id: string | null;
}

export interface CustomerProfile {
  created_at: Generated<Timestamp>;
  marketing_opt_in: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Invoice {
  booking_id: string;
  customer_address: string;
  customer_name: string;
  discount_paise: number;
  document_object_key: string | null;
  id: Generated<string>;
  invoice_number: string;
  issued_at: Generated<Timestamp>;
  issuer_address: string;
  issuer_gstin: string | null;
  issuer_legal_name: string;
  lines: Json;
  subtotal_paise: number;
  tax_paise: number;
  total_paise: number;
}

export interface InvoiceSequence {
  next_value: Generated<number>;
  series: string;
}

export interface JobLease {
  job_name: string;
  locked_until: Timestamp;
  owner: string;
}

export interface JobRun {
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<number>;
  job_name: string;
  processed: Generated<number>;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
}

export interface LegalDocument {
  code: string;
  content_sha256: string;
  created_at: Generated<Timestamp>;
  effective_from: Timestamp;
  id: Generated<string>;
  locale: string;
  title: string;
  url: string;
  version: string;
}

export interface Locale {
  code: string;
  is_active: Generated<boolean>;
  name: string;
  native_name: string;
  sort_order: Generated<number>;
}

export interface Locality {
  center_lat: Numeric | null;
  center_lng: Numeric | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  pincode: string;
  updated_at: Generated<Timestamp>;
  zone_id: string;
}

export interface Notification {
  attempts: Generated<number>;
  booking_id: string | null;
  channel: string;
  created_at: Generated<Timestamp>;
  dedupe_key: string;
  delivered_at: Timestamp | null;
  id: Generated<string>;
  last_error: string | null;
  locale: string;
  next_attempt_at: Generated<Timestamp>;
  provider_message_id: string | null;
  read_at: Timestamp | null;
  sent_at: Timestamp | null;
  status: Generated<string>;
  template_id: string;
  user_id: string;
  variables: Generated<Json>;
}

export interface NotificationTemplate {
  body: string;
  channel: string;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  locale: string;
  provider_template_id: string | null;
  title: string | null;
  version: number;
}

export interface OtpChallenge {
  attempts: Generated<number>;
  client_app: string;
  code_hash: string;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  delivery_error: string | null;
  delivery_reference: string | null;
  delivery_status: Generated<string>;
  expires_at: Timestamp;
  id: Generated<string>;
  max_attempts: Generated<number>;
  phone_e164: string;
  purpose: string;
  request_ip: string | null;
}

export interface Payment {
  amount_paise: number;
  authorized_at: Timestamp | null;
  booking_id: string;
  captured_amount_paise: number | null;
  captured_at: Timestamp | null;
  cash_receipt_number: string | null;
  checkout: Json | null;
  collected_by: string | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  failure_reason: string | null;
  id: Generated<string>;
  idempotency_key: string;
  is_duplicate: Generated<boolean>;
  method: string | null;
  provider: string;
  provider_order_id: string | null;
  provider_payment_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PaymentEvent {
  event_type: string;
  id: Generated<number>;
  payload: Json;
  payment_id: string | null;
  processed_at: Timestamp | null;
  processing_error: string | null;
  provider: string;
  provider_event_id: string;
  received_at: Generated<Timestamp>;
  refund_id: string | null;
  signature_verified: boolean;
}

export interface PayoutRule {
  base_payout_paise: number;
  city_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  end_minute: number | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  priority: Generated<number>;
  service_id: string;
  service_option_id: string | null;
  start_minute: number | null;
  travel_allowance_paise: Generated<number>;
  updated_at: Generated<Timestamp>;
  valid_from: Timestamp;
  valid_to: Timestamp | null;
  weekdays: number[] | null;
  zone_id: string | null;
}

export interface Permission {
  code: string;
  description: string;
  is_sensitive: Generated<boolean>;
}

export interface Pincode {
  city_id: string;
  code: string;
  created_at: Generated<Timestamp>;
  is_active: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface PriceRule {
  base_amount_paise: number;
  city_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  end_minute: number | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  notes: string | null;
  priority: Generated<number>;
  service_id: string;
  service_option_id: string | null;
  start_minute: number | null;
  tax_rate_code: string;
  updated_at: Generated<Timestamp>;
  valid_from: Timestamp;
  valid_to: Timestamp | null;
  weekdays: number[] | null;
  zone_id: string | null;
}

export interface Promotion {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string;
  discount_type: string;
  first_booking_only: Generated<boolean>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  max_discount_paise: number | null;
  max_redemptions: number | null;
  max_redemptions_per_user: Generated<number>;
  min_order_paise: number | null;
  updated_at: Generated<Timestamp>;
  valid_from: Timestamp;
  valid_to: Timestamp;
  value: number;
}

export interface PromotionCity {
  city_id: string;
  promotion_id: string;
}

export interface PromotionRedemption {
  booking_id: string;
  created_at: Generated<Timestamp>;
  discount_paise: number;
  id: Generated<string>;
  promotion_id: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PromotionService {
  promotion_id: string;
  service_id: string;
}

export interface Refund {
  amount_paise: number;
  booking_id: string;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision_note: string | null;
  decision_policy: string | null;
  failure_reason: string | null;
  id: Generated<string>;
  idempotency_key: string;
  payment_id: string;
  processed_at: Timestamp | null;
  provider_refund_id: string | null;
  reason_code: string;
  reason_text: string;
  requested_by: string | null;
  requested_source: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Role {
  code: string;
  description: string;
  is_staff: boolean;
  name: string;
}

export interface RolePermission {
  permission_code: string;
  role_code: string;
}

export interface SafetyIncident {
  booking_id: string | null;
  category: string;
  closed_at: Timestamp | null;
  closed_by: string | null;
  closure_summary: string | null;
  commander_user_id: string | null;
  id: Generated<string>;
  idempotency_key: string | null;
  incident_code: Generated<string>;
  lat: Numeric | null;
  lng: Numeric | null;
  location_text: string | null;
  occurred_at: Generated<Timestamp>;
  reported_at: Generated<Timestamp>;
  reported_by_user_id: string;
  reporter_role: string;
  request_hash: string | null;
  review_due_at: Timestamp | null;
  severity: string;
  source: string;
  status: Generated<string>;
  summary: string;
  updated_at: Generated<Timestamp>;
}

export interface SafetyIncidentEvent {
  actor_user_id: string | null;
  body: string;
  event_type: string;
  from_status: string | null;
  id: Generated<number>;
  incident_id: string;
  occurred_at: Generated<Timestamp>;
  source: string;
  to_status: string | null;
}

export interface Service {
  attributes: Generated<Json>;
  buffer_after_minutes: Generated<number>;
  buffer_before_minutes: Generated<number>;
  category_id: string;
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  duration_minutes: number;
  fulfilment_type: Generated<string>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  max_advance_days: Generated<number>;
  min_lead_time_minutes: Generated<number>;
  name: string;
  offer_timeout_seconds: Generated<number>;
  payment_hold_minutes: Generated<number>;
  requires_start_code: Generated<boolean>;
  sort_order: Generated<number>;
  supports_instant: Generated<boolean>;
  supports_scheduled: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  workers_required: Generated<number>;
}

export interface ServiceableLocality {
  center_lat: Numeric | null;
  center_lng: Numeric | null;
  city_code: string | null;
  city_id: string | null;
  locality_id: string | null;
  locality_name: string | null;
  pincode: string | null;
  service_radius_m: number | null;
  time_zone: string | null;
  zone_code: string | null;
  zone_id: string | null;
}

export interface ServiceCategory {
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  icon_key: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  parent_id: string | null;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface ServiceOption {
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  duration_minutes: number | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_default: Generated<boolean>;
  name: string;
  service_id: string;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface ServiceTask {
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_default_selected: Generated<boolean>;
  name: string;
  service_id: string;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface ServiceTrainingRequirement {
  module_code: string;
  service_id: string;
}

export interface ServiceVerificationRequirement {
  service_id: string;
  verification_type: string;
}

export interface ServiceZone {
  created_at: Generated<Timestamp>;
  is_active: Generated<boolean>;
  notes: string | null;
  service_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  zone_id: string;
}

export interface StaffCredential {
  failed_attempts: Generated<number>;
  locked_until: Timestamp | null;
  mfa_enrolled_at: Timestamp | null;
  password_changed_at: Generated<Timestamp>;
  password_hash: string;
  totp_last_used_step: number | null;
  totp_pending_secret_encrypted: Buffer | null;
  totp_secret_encrypted: Buffer | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface StaffLoginChallenge {
  attempts: Generated<number>;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  max_attempts: Generated<number>;
  purpose: string;
  token_hash: string;
  user_id: string;
}

export interface SupportCase {
  booking_id: string | null;
  case_code: Generated<string>;
  category: string;
  closed_at: Timestamp | null;
  description: string;
  desired_resolution: string | null;
  id: Generated<string>;
  idempotency_key: string | null;
  next_update_due_at: Timestamp | null;
  opened_at: Generated<Timestamp>;
  owner_user_id: string | null;
  raised_by_role: string;
  raised_by_user_id: string;
  request_hash: string | null;
  resolution_summary: string | null;
  resolved_at: Timestamp | null;
  safety_incident_id: string | null;
  severity: Generated<string>;
  source: string;
  status: Generated<string>;
  subject: string;
  updated_at: Generated<Timestamp>;
}

export interface SupportCaseEvent {
  actor_user_id: string | null;
  body: string | null;
  case_id: string;
  event_type: string;
  from_status: string | null;
  id: Generated<number>;
  is_internal: Generated<boolean>;
  occurred_at: Generated<Timestamp>;
  source: string;
  to_status: string | null;
}

export interface TaxRate {
  code: string;
  created_at: Generated<Timestamp>;
  effective_from: Timestamp;
  effective_to: Timestamp | null;
  id: Generated<string>;
  name: string;
  rate_bp: number;
}

export interface TrainingModule {
  code: string;
  description: string | null;
  is_active: Generated<boolean>;
  name: string;
}

export interface Translation {
  entity_id: string;
  entity_type: string;
  field: string;
  locale: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface UserDevice {
  app_version: string | null;
  client_app: string;
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
  id: Generated<string>;
  last_seen_at: Generated<Timestamp>;
  locale: string | null;
  platform: string;
  push_token: string | null;
  user_id: string;
}

export interface UserRole {
  city_id: string | null;
  granted_at: Generated<Timestamp>;
  granted_by: string | null;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  role_code: string;
  user_id: string;
}

export interface WorkerBankAccount {
  account_holder_name: string;
  account_number_encrypted: Buffer;
  account_number_last4: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  ifsc: string;
  status: Generated<string>;
  submitted_by: string;
  updated_at: Generated<Timestamp>;
  verified_at: Timestamp | null;
  verified_by: string | null;
  worker_id: string;
}

export interface WorkerEarning {
  amount_paise: number;
  booking_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string;
  earning_type: string;
  hold_reason: string | null;
  id: Generated<string>;
  payout_id: string | null;
  payout_rule_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  worker_id: string;
}

export interface WorkerPayout {
  approved_at: Timestamp | null;
  approved_by: string | null;
  bank_reference: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  paid_at: Timestamp | null;
  period_end: string;
  period_start: string;
  prepared_by: string;
  status: Generated<string>;
  total_paise: number;
  updated_at: Generated<Timestamp>;
  worker_id: string;
}

export interface WorkerPresence {
  changed_at: Generated<Timestamp>;
  is_online: Generated<boolean>;
  last_lat: Numeric | null;
  last_lng: Numeric | null;
  last_location_at: Timestamp | null;
  worker_id: string;
}

export interface WorkerPresenceEvent {
  id: Generated<number>;
  is_online: boolean;
  occurred_at: Generated<Timestamp>;
  source: string;
  worker_id: string;
}

export interface WorkerProfile {
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  date_of_birth: string | null;
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  gender: string | null;
  home_address_id: string | null;
  languages: Generated<string[]>;
  primary_zone_id: string | null;
  status: Generated<string>;
  status_reason: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
  worker_code: string;
}

export interface WorkerReservation {
  booking_id: string;
  created_at: Generated<Timestamp>;
  crew_slot: Generated<number>;
  hold_expires_at: Timestamp | null;
  id: Generated<string>;
  period: string;
  release_reason: string | null;
  released_at: Timestamp | null;
  status: string;
  worker_id: string;
}

export interface WorkerRestriction {
  id: Generated<string>;
  imposed_at: Generated<Timestamp>;
  imposed_by: string;
  lift_reason: string | null;
  lifted_at: Timestamp | null;
  lifted_by: string | null;
  reason: string;
  review_at: Timestamp;
  service_id: string | null;
  worker_id: string;
  zone_id: string | null;
}

export interface WorkerServicePermission {
  granted_at: Generated<Timestamp>;
  granted_by: string;
  id: Generated<string>;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  service_id: string;
  valid_until: Timestamp | null;
  worker_id: string;
  zone_id: string | null;
}

export interface WorkerShift {
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  period: string;
  status: Generated<string>;
  worker_id: string;
  zone_id: string;
}

export interface WorkerStatusHistory {
  actor_role: string | null;
  actor_user_id: string | null;
  from_status: string | null;
  id: Generated<number>;
  occurred_at: Generated<Timestamp>;
  reason: string | null;
  request_id: string | null;
  source: string;
  to_status: string;
  worker_id: string;
}

export interface WorkerStatusTransition {
  from_status: string;
  requires_reason: boolean;
  sources: string[];
  to_status: string;
}

export interface WorkerTraining {
  assessed_at: Timestamp | null;
  assessed_by: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: Generated<string>;
  module_code: string;
  score: number | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  worker_id: string;
}

export interface WorkerVerification {
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  document_object_key: string | null;
  expires_at: Timestamp | null;
  id: Generated<string>;
  method: string | null;
  notes: string | null;
  reference_masked: string | null;
  rejection_reason: string | null;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  verification_type: string;
  worker_id: string;
}

export interface Zone {
  boundary_geojson: Json | null;
  center_lat: Numeric;
  center_lng: Numeric;
  city_id: string;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  service_radius_m: number;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  address: Address;
  app_user: AppUser;
  audit_log: AuditLog;
  auth_session: AuthSession;
  booking: Booking;
  booking_assignment: BookingAssignment;
  booking_price_line: BookingPriceLine;
  booking_rating: BookingRating;
  booking_schedule_change: BookingScheduleChange;
  booking_status_history: BookingStatusHistory;
  booking_status_transition: BookingStatusTransition;
  booking_task: BookingTask;
  booking_verification_code: BookingVerificationCode;
  business_setting: BusinessSetting;
  cancellation_rule: CancellationRule;
  charge_rule: ChargeRule;
  city: City;
  consent_record: ConsentRecord;
  credit_note: CreditNote;
  customer_profile: CustomerProfile;
  invoice: Invoice;
  invoice_sequence: InvoiceSequence;
  job_lease: JobLease;
  job_run: JobRun;
  legal_document: LegalDocument;
  locale: Locale;
  locality: Locality;
  notification: Notification;
  notification_template: NotificationTemplate;
  otp_challenge: OtpChallenge;
  payment: Payment;
  payment_event: PaymentEvent;
  payout_rule: PayoutRule;
  permission: Permission;
  pincode: Pincode;
  price_rule: PriceRule;
  promotion: Promotion;
  promotion_city: PromotionCity;
  promotion_redemption: PromotionRedemption;
  promotion_service: PromotionService;
  refund: Refund;
  role: Role;
  role_permission: RolePermission;
  safety_incident: SafetyIncident;
  safety_incident_event: SafetyIncidentEvent;
  service: Service;
  service_category: ServiceCategory;
  service_option: ServiceOption;
  service_task: ServiceTask;
  service_training_requirement: ServiceTrainingRequirement;
  service_verification_requirement: ServiceVerificationRequirement;
  service_zone: ServiceZone;
  serviceable_locality: ServiceableLocality;
  staff_credential: StaffCredential;
  staff_login_challenge: StaffLoginChallenge;
  support_case: SupportCase;
  support_case_event: SupportCaseEvent;
  tax_rate: TaxRate;
  training_module: TrainingModule;
  translation: Translation;
  user_device: UserDevice;
  user_role: UserRole;
  worker_bank_account: WorkerBankAccount;
  worker_earning: WorkerEarning;
  worker_payout: WorkerPayout;
  worker_presence: WorkerPresence;
  worker_presence_event: WorkerPresenceEvent;
  worker_profile: WorkerProfile;
  worker_reservation: WorkerReservation;
  worker_restriction: WorkerRestriction;
  worker_service_permission: WorkerServicePermission;
  worker_shift: WorkerShift;
  worker_status_history: WorkerStatusHistory;
  worker_status_transition: WorkerStatusTransition;
  worker_training: WorkerTraining;
  worker_verification: WorkerVerification;
  zone: Zone;
}
